### ISSUE TITLE
LogOn() and LogOnAnonymous() not working in Unity 5.6.5f1 and Steamworks.NET 9.0.0

### ISSUE THREAD

**Issue by Dimolade** [rlabrecque/Steamworks.NET#547]
hi im trying to make a working steam port for the 3ds. im using the best possible version for Nintendo 3DS Support and matching Version Steamworks.Net 9.0.0. im trying to create the login but it doesent work since LogOn() and LogOnAnonymous() dont Work. Assets/LowerLCDScript.cs(11,13): error CS0117: `Steamworks.SteamUser' does not contain a definition for `LogOn'
