### ISSUE TITLE
Error when updating to 11.1.0 | Unity 2017.2.1p3 | from Master / d67945513bc89b1b9b5d401c0b72d7df5bdc75da

### ISSUE THREAD

**Issue by AskAnEnemyStudios** [rlabrecque/Steamworks.NET#225]
I tried updating to the latest version since I keep getting issues when building UWP

I continue to get the following errors when building to **Standalone:**

Assets/Plugins/Steamworks.NET/autogen/isteamunifiedmessages.cs(22,54): error CS0117: `Steamworks.NativeMethods' does not contain a definition for `ISteamUnifiedMessages_SendMethod'

Assets/Plugins/Steamworks.NET/autogen/isteamunifiedmessages.cs(31,25): error CS0117: `Steamworks.NativeMethods' does not contain a definition for `ISteamUnifiedMessages_GetMethodResponseInfo'

Assets/Plugins/Steamworks.NET/autogen/isteamunifiedmessages.cs(39,25): error CS0117: `Steamworks.NativeMethods' does not contain a definition for `ISteamUnifiedMessages_GetMethodResponseData'

Assets/Plugins/Steamworks.NET/autogen/isteamunifiedmessages.cs(47,25): error CS0117: `Steamworks.NativeMethods' does not contain a definition for `ISteamUnifiedMessages_ReleaseMethod'

Assets/Plugins/Steamworks.NET/autogen/isteamunifiedmessages.cs(57,26): error CS0117: `Steamworks.NativeMethods' does not contain a definition for `ISteamUnifiedMessages_SendNotification'

And these errors when building for UWP:

Assets/Plugins/Steamworks.NET/autogen/isteamunifiedmessages.cs(29,110): error CS0246: The type or namespace name `EResult' could not be found. Are you missing an assembly reference?

Assets/Plugins/Steamworks.NET/types/SteamClient/SteamAPI_PostAPIResultInProcess_t.cs(9,57): error CS0246: The type or namespace name `SteamAPICall_t' could not be found. Are you missing an assembly reference?

**Comment by rlabrecque** [comment]
Mmmmm, hrm since Valve deleted ISteamUnifiedMessages it's just gone from master which means it didn't get overwritten when you upgraded, might have to throw in an empty file for that one to prevent this.

Possibly the same thing for StemaAPI_PostAPIResultInProcess_t?

**Comment by AskAnEnemyStudios** [comment]
I'm not gonna live I have no clue what you mean by "throw in an empty file" hahaha

**Comment by WestwoodForever** [comment]
Delete the isteamunifiedmessages.cs file. It is solved with that.

**Comment by AskAnEnemyStudios** [comment]
Hey thanks @WestwoodForever that worked to remove the error for a Standalone build, but now when I try to do a proper UWP build I get the following error

Assets/Plugins/Steamworks.NET/types/SteamClient/SteamAPI_PostAPIResultInProcess_t.cs(9,57): error CS0246: The type or namespace name `SteamAPICall_t' could not be found. Are you missing an assembly reference?

**Comment by AskAnEnemyStudios** [comment]
added UNITY_SWITCH as one of the platforms for DISABLESTEAMWORKS ;)
